### ISSUE TITLE
Gem: dub

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#150]
Idea: Give a short intro to dub, examples for different use-cases and ideally how to integrate with one's favorite build system.

Ping @s-ludwig.

**Comment by stonemaster** [comment]
#27 must be implemented beforehand

**Comment by stonemaster** [comment]
@wilzbach suggestions:
> how to create a static,dyn library using dmd
>how to link a static, dyn library using dmd

**Comment by wilzbach** [comment]
Pinging regular contributors to dub @mdondorff @MartinNowak @grogancolin @p0nce @Geod24.
Has someone time to write a short gem (=tour section) about DUB and simple, common use cases?
The target audience is mostly newcomers to D.

FYI #27 is not needed for this (#27 is about the tour getting support for DUB packages).

**Comment by Geod24** [comment]
Something along the lines of https://github.com/dlang/dub/wiki/Cookbook ?
It might need an update though.

**Comment by wilzbach** [comment]
> Something along the lines of https://github.com/dlang/dub/wiki/Cookbook ?
> It might need an update though.

That looks pretty nice already :)
One issue is that the tour currently allows only one example on the right hand side, so a good example that covers a couple of common cases is probably needed.
Btw for impression of other "Gems":

http://tour.dlang.org/tour/en/gems/uniform-function-call-syntax-ufcs
http://tour.dlang.org/tour/en/gems/subtyping

**Comment by ZombineDev** [comment]
@wilzbach count me in :P
I think we should do a series of chapters (like on vibe.d), because Dub is integral part of D's ecosystem. It's hard to (maybe even impossible) to do one example that would cover mosy common use cases.

Probably the right-hand side should be used for writing dub.sdl.

I think what most newcomers find missing is guide similar to Rust's [Cargo guide](http://doc.crates.io/guide.html) and Haskell's wiki on [writing Haskell programs](https://wiki.haskell.org/How_to_write_a_Haskell_program). I think @mdparker and @redstar cover some of that in their books, but I think it would be nice to have it also on tour.

**Comment by wilzbach** [comment]
This issue was moved to dlang-tour/english#8
