### ISSUE TITLE
put external scripts to bottom - avoids blocking the rendering

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#155]
Script should be put before the closing body html tag, s.t. the scripts don't block the download the rest of the document. Maybe not angular, but everything external (Bootstrap, codemirror, GoogleAnalytics, ...).

**Comment by stonemaster** [comment]
I am not a web expert. I already did some stuff according to google page insights. I think all resources currently at the top are needed for rendering (bootstrap, angular looks ugly first when at the bottom). Also code mirror needs to be at the top because I use an angular extension that needs cod mirror to be there.

**Comment by wilzbach** [comment]
Alrighty - if it's we depend on the cache it's not dry important anyhow
