### ISSUE TITLE
Array example Caesar isn't well suited

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#227]
1) it either requires loops or ranges (both haven't explained before)
2) it requires casting (or knowing how to omit that by defining to char variables)
3) it requires knowledge about ASCII (which we would at least have to explain)
4) it's non-idiomatic D, because we usually do stuff lazily 

That being said, here's my "idiomatic" solution:

```d
import std.array: array;
import std.algorithm: map;
return input.map!((x) => cast(char) (((x - 97) + shift) % 26 + 97)).array;
```

**Comment by stonemaster** [comment]
There definitely a solution for the array example using the `result[] OP= ...` syntax. I just don't have it anymore :-) So no need to use loops or any range operations. I agree it's a complicated example but I think it's nice to have some more advanced exercise. I liked that in the Gotour too. 
But I noticed that another sentence is needed for the mathematical array operations that emphasises that those operations also possible with single values (like `result[] -= 'a'`).
I'll post a solution when I got the time to re-invent it :-)

**Comment by stonemaster** [comment]
The solution without any ranges and loops:
```d
char[] encrypt(char[] input, char shift)
{
    auto result = input.dup;
    result[] -= 'a';
    result[] += shift;
    result[] %= 26;
    result[] += 'a';
    return result;
}
```

**Comment by i-am-cyrus** [comment]
Nice solution. But isn't by doing `result[] -= 'a';` you are using the assumption that a-z is situated in memory sequential? Maybe it will be better to add info about that into Exercise description?

**Comment by wilzbach** [comment]
> you are using the assumption that a-z is situated in memory sequentialy

It's not an "assumption", it's how ascii is defined ;-)

> Maybe it will be better to add info about that into Exercise description?

Sure, do you have sth. specific in mind?
(https://github.com/dlang-tour/english/blob/master/basics/arrays.md)

**Comment by wilzbach** [comment]
> Maybe it will be better to add info about that into Exercise description?

A tiny step forward, s.t. people at least have an easier time finding this discussion:

https://github.com/dlang-tour/english/pull/225

**Comment by GordonHarley** [comment]
I did it like this. 

result[] = ((result[] - 'a' + shift) % 26) + 'a';

My first try was subtracting shift and failed because of that, but it works when shift is applied correctly.   I came here to check whether arr[] was valid on the RHS in that form of assignment and found my actual mistake.   :-)

**Comment by jmafc** [comment]
None of these solutions work with EBCDIC input, because it has gaps between 'i' - 'j' and 'r' - 's'. My proposed solution would use an `auto cipher = "abcdefghijklmnopqrstuvwxyz";`. It would have to use a loop and only encrypt a `result[i]` if the character was in the cipher. It would then apply the shift to the `cipher`, but taking care that if the shift goes beyond 'z', it would subtract `cipher.length` to index from the `a`, and replace the `result[i]` with the corresponding letter from `cipher`.

**Comment by mark-summerfield** [comment]
I think that this tour page should mention that although `new` is used, there is no need to worry about freeing the memory, e.g.,:

> Unlike in C/C++, you don't have to worry about freeing the `new`-ed memory, since D's garbage collector takes care of it automatically at the right time.
