### ISSUE TITLE
Language as part of the URL

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#262]
As #132 is getting closer, we probably want to put the language into the URL, so instead of `tour.dlang.io/tour/basics/ranges` we could use `tour.dlang.io/en/basics/ranges` or if needed for clarity `tour.dlang.io/tour/en/basics/ranges`.

**Comment by stonemaster** [comment]
That's right. We should definitly do that otherwise we would mee to rely on cookies or something similar for language selection.
I would definitely go with the `tour` Prefix in case we add some other paths later on.
And we should make sure not to invalidate old links by defaulting to `en` If nothing is passed.
